### ISSUE TITLE
Sleep Problem

### ISSUE THREAD

**Issue by dinhchi27** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#16]
Hello, i have same Hardware with you. and i use your EFI
But The computer goes to sleep, but the fan is still running. 
Can you help.

**Comment by VanXNF** [comment]
Hello, I don't know what caused your problem.
When my computer goes to sleep, it usually takes about 20s. And during this time, the fan is still running too. Finally, the fan stopped running.
Since my fans are directly connected to the motherboard, they work normally, so I want to know whether your fan is directly connected to the motherboard or powered directly from the power supply
